name: hello-world
on: push
name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps;
    - name: Check out repository code
      uses: actions/checkout@v3

    # Add more steps as needed for your workflow

        - run: echo "$(cat hello_world.txt)"
